spring:
  application:
    name:GetWay
  cloud:
    zookeeper:
      connect-string: localhost:2181,localhost:2182,localhost:2183
    dependencies:
      Test1:
        path: /Test1
        loadBalancerType: RANDOM
        contentTypeTemplate: application/vnd.zooService.$version+json
        version: v1
        headers:
          header1:
            - value1
          header2:
            - value2
        required: false
        stubs: org.springframework:foo:stubs
zuul:
  prefix: /proxy
  routes:
    test:
      path: /redirect/**
      url: http://www.google.com
      sensitiveHeaders:
    customer-by-address:
      path: /customer-by-address/**
      url: http://localhost:9098
      sensitiveHeaders:
    customer-by-service:
      # demo url http://localhost:8888/zuulApi/clientApi1/client1/getUserData/Tim
      path: /clientApi1/**
      serviceId: client-service 
      sensitiveHeaders:
      #stripPrefix: false
    oauth-service:
      path: /OauthApi/**
      serviceId: Oauth 
      sensitiveHeaders: 
    resource-service:
      path: /ResourceApi/**
      serviceId: Resource 
      sensitiveHeaders:  
security:
  oauth2:
    client:
      access-token-uri:http://localhost:9998/oauth/token
      user-authorization-uri:http://localhost:9998/oauth/authorize
      client-Id:clientId1
      client-Secret:123qwe
      grant-Type:password
      scope:select
      username:tim
      password:123qwe
    resource:
      user-info-uri:http://Resource/user
      prefer-token-info:false            